### ISSUE TITLE
NeoRunner issue

### ISSUE THREAD

**Issue by 0Gaines0** [BenGH28/nvim#13]
Hey Ben, sorry to bother. Have you ever seen this issue with your neoRunner plugin ??

![Screenshot 2024-03-19 161853](https://github.com/BenGH28/nvim/assets/122590456/604c360e-f627-473c-b90e-c724edeb9cdc)

Thank you !

**Comment by BenGH28** [comment]
I'm not maintaining neorunner and have archived it last month.  You're better off looking at a different plugin like [code_runner.nvim](https://github.com/CRAG666/code_runner.nvim).
